# Generated by Django 4.1.7 on 2023-04-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('AD_USER_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'AD_USER',
            },
        ),
    ]
