# Generated by Django 4.1.7 on 2023-04-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='CIS_AC.AD_USER',
        ),
    ]
