# Generated by Django 4.1.7 on 2023-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CisAcAdUser',
            fields=[
                ('ad_user_id', models.CharField(db_column='AD_USER_ID', max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=50, null=True)),
            ],
            options={
                'db_table': 'CIS_AC.AD_USER',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
