# Generated by Django 4.1.7 on 2023-04-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_cisacaduser_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CisAcAdUser',
        ),
    ]
