# Generated by Django 4.0 on 2023-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hostname',
        ),
        migrations.AddField(
            model_name='profile',
            name='CISDB_hostname',
            field=models.CharField(default='db-host-b.internal.example.com', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='CISDB_password',
            field=models.CharField(default='DB_PASSWORD', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='CISDB_servicename',
            field=models.CharField(default='cissrv_rdo', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='CISDB_username',
            field=models.CharField(default='app_user', max_length=30),
        ),
    ]
