# Generated by Django 4.0 on 2023-06-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_remove_profile_hostname_profile_cisdb_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CISDB_port',
            field=models.CharField(default='1521', max_length=30),
        ),
    ]
