# Generated by Django 4.0 on 2023-06-20 10:35

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0007_profile_cisdb_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('CISDB_username', models.CharField(default='app_user', max_length=30)),
                ('CISDB_password', models.CharField(default='DB_PASSWORD', max_length=30)),
                ('CISDB_hostname', models.CharField(default='db-host-b.internal.example.com', max_length=30)),
                ('CISDB_port', models.CharField(default='1521', max_length=30)),
                ('CISDB_servicename', models.CharField(default='cissrv_rdo', max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
