# Generated by Django 4.0 on 2023-06-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0009_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CISDB_username', models.CharField(default='app_user', max_length=30)),
                ('CISDB_password', models.CharField(default='DB_PASSWORD', max_length=30)),
                ('CISDB_hostname', models.CharField(default='db-host-b.internal.example.com', max_length=30)),
                ('CISDB_port', models.CharField(default='1521', max_length=30)),
                ('CISDB_servicename', models.CharField(default='cissrv_rdo', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
