# Generated by Django 4.0 on 2023-06-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0010_account_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='CISDB',
        ),
    ]
