# Generated by Django 4.0 on 2023-07-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0011_rename_account_cisdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='auth.user'),
        ),
    ]
