# Generated by Django 4.0 on 2023-07-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
