# Generated by Django 4.0 on 2023-07-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0014_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWHDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('DWHDB_username', models.CharField(default='DB_USER', max_length=30)),
                ('DWHDB_password', models.CharField(default='Heslo_555', max_length=30)),
                ('DWHDB_hostname', models.CharField(default='ADB01.internal.example.com', max_length=30)),
                ('DWHDB_port', models.CharField(default='1539', max_length=30)),
                ('DWHDB_servicename', models.CharField(default='dwh', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cisdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='cisdb',
            name='CISDB_username',
            field=models.CharField(default='DB_USER', max_length=30),
        ),
        migrations.AlterField(
            model_name='cisdb',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
        ),
    ]
