# Generated by Django 4.0 on 2023-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_dwhdb_remove_cisdb_id_alter_cisdb_cisdb_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb',
            name='CISDB_password',
            field=models.CharField(default='YourPassword#01', max_length=30),
        ),
        migrations.AlterField(
            model_name='dwhdb',
            name='DWHDB_password',
            field=models.CharField(default='YourPassword#01', max_length=30),
        ),
    ]
