# Generated by Django 4.0 on 2023-07-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_alter_cisdb_cisdb_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb',
            name='CISDB_username',
            field=models.CharField(default='Meno_Priezvisko', max_length=30),
        ),
        migrations.AlterField(
            model_name='dwhdb',
            name='DWHDB_username',
            field=models.CharField(default='Meno_Priezvisko', max_length=30),
        ),
    ]
