# Generated by Django 4.0 on 2023-07-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_alter_cisdb_cisdb_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb',
            name='CISDB_username',
            field=models.CharField(default='Name_Surname', max_length=30),
        ),
        migrations.AlterField(
            model_name='dwhdb',
            name='DWHDB_username',
            field=models.CharField(default='Name_Surname', max_length=30),
        ),
    ]
