# Generated by Django 4.0 on 2023-11-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0018_alter_cisdb_cisdb_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CISDB_TEST',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('CISDB_username', models.CharField(default='Name_Surname', max_length=30)),
                ('CISDB_password', models.CharField(default='YourPassword#01', max_length=30)),
                ('CISDB_hostname', models.CharField(default='db-host-b.internal.example.com', max_length=30)),
                ('CISDB_port', models.CharField(default='1521', max_length=30)),
                ('CISDB_servicename', models.CharField(default='cissrv_rdo', max_length=30)),
            ],
        ),
    ]
