# Generated by Django 4.0 on 2023-12-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0019_cisdb_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='BILLDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('BILLDB_username', models.CharField(default='username', max_length=30)),
                ('BILLDB_password', models.CharField(default='YourPassword#01', max_length=30)),
                ('BILLDB_hostname', models.CharField(default='scan-billdb.etc.example', max_length=30)),
                ('BILLDB_port', models.CharField(default='1521', max_length=30)),
                ('BILLDB_servicename', models.CharField(default='billdb.etc.example.sk', max_length=30)),
            ],
        ),
    ]
