# Generated by Django 4.0 on 2023-12-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_billdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cisdb_test',
            old_name='CISDB_hostname',
            new_name='CISDB_TEST_hostname',
        ),
        migrations.RenameField(
            model_name='cisdb_test',
            old_name='CISDB_password',
            new_name='CISDB_TEST_password',
        ),
        migrations.RenameField(
            model_name='cisdb_test',
            old_name='CISDB_port',
            new_name='CISDB_TEST_port',
        ),
        migrations.RenameField(
            model_name='cisdb_test',
            old_name='CISDB_servicename',
            new_name='CISDB_TEST_servicename',
        ),
        migrations.RenameField(
            model_name='cisdb_test',
            old_name='CISDB_username',
            new_name='CISDB_TEST_username',
        ),
    ]
