# Generated by Django 4.0 on 2023-12-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_rename_cisdb_hostname_cisdb_test_cisdb_test_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb_test',
            name='CISDB_TEST_password',
            field=models.IntegerField(default='YourPassword#01', max_length=90),
        ),
    ]
