# Generated by Django 4.0 on 2023-12-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_alter_cisdb_test_cisdb_test_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb_test',
            name='CISDB_TEST_password',
            field=models.CharField(default='YourPassword#01', max_length=128),
        ),
    ]
