# Generated by Django 4.0 on 2023-12-17 21:59

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_alter_cisdb_test_cisdb_test_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb_test',
            name='CISDB_TEST_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
