# Generated by Django 4.0 on 2023-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_alter_cisdb_test_cisdb_test_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwhdb',
            name='DWHDB_password',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
