# Generated by Django 4.0 on 2023-12-26 14:19

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0030_alter_dwhdb_dwhdb_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb_test',
            name='CISDB_TEST_password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='dwhdb',
            name='DWHDB_password',
            field=models.CharField(default='YourPassword#01', max_length=30),
        ),
    ]
