# Generated by Django 3.2.23 on 2023-12-27 13:33

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_alter_cisdb_test_cisdb_test_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdb',
            name='BILLDB_password',
            field=encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01'),
        ),
    ]
