# Generated by Django 3.2.23 on 2023-12-27 13:46

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_alter_billdb_billdb_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisdb',
            name='CISDB_password',
            field=encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01'),
        ),
        migrations.AlterField(
            model_name='dwhdb',
            name='DWHDB_password',
            field=encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01'),
        ),
    ]
