# Generated by Django 3.2.23 on 2023-12-28 06:38

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0033_auto_20231227_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMS_DWHDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('EMS_DWHDB_username', models.CharField(default='Name', max_length=30)),
                ('EMS_DWHDB_password', encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01')),
                ('EMS_DWHDB_hostname', models.CharField(default='scan-dwh.etc.example', max_length=30)),
                ('EMS_DWHDB_port', models.CharField(default='1521', max_length=30)),
                ('EMS_DWHDB_servicename', models.CharField(default='dwh', max_length=30)),
            ],
        ),
    ]
