"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import pytz

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Načíta premenné z .env súboru (mimo gitu)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("Chýba DJANGO_SECRET_KEY – skopíruj .env.example do .env a vyplň ho.")


# Kľúč na šifrovanie citlivých polí (encrypted_model_fields) – z .env
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

PASSWORD_HASHERS = [

    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',

    'django.contrib.auth.hashers.BCryptPasswordHasher',

    'django.contrib.auth.hashers.PBKDF2PasswordHasher',

    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',

]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # 'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'work.apps.WorkConfig',
    'crispy_forms',
    'jazzmin', #admin alternative
    'encrypted_model_fields',
    'eets.apps.EetsConfig',
    'edz.apps.EdzConfig',
    'apscheduler', #scheduler
    'django_apscheduler', #scheduler
    # 'django_apscheduler.apps.DjangoAPSchedulerConfig',

    
]

#appscheduler

# Format string for displaying run time timestamps in the Django admin site. The default
# just adds seconds to the standard Django format, which is useful for displaying the timestamps
# for jobs that are scheduled to run on intervals of less than one minute.
# See https://docs.djangoproject.com/en/dev/ref/settings/#datetime-format for format string
# syntax details.
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
# Maximum run time allowed for jobs that are triggered manually via the Django admin site, which
# prevents admin site HTTP requests from timing out.
# Longer running jobs should probably be handed over to a background task processing library
# that supports multiple background worker processes instead (e.g. Dramatiq, Celery, Django-RQ,
# etc. See: https://djangopackages.org/grids/g/workers-queues-tasks/ for popular options).
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# APSCHEDULER_DATABASE_ALIAS = 'default' # the name of the database alias to use for scheduler
# APSCHEDULER_DATABASE = BASE_DIR / "db.sqlite3"
# APSCHEDULER_RUN_NOW_TIMEOUT = 25
# SCHEDULER_CONFIG = {
#     "apscheduler.jobstores.default": {
#         "class": "django_apscheduler.jobstores:DjangoJobStore"
#     },
#     'apscheduler.executors.processpool': {
#         "type": "threadpool"
#     },
# }
# SCHEDULER_AUTOSTART = True

# AUTH_USER_MODEL = "work.User"



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# EMAILS
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# con_CISDB_STDBY = cx_Oracle.connect("DB_USER/DB_PASSWORD@db-host-b.internal.example.com:1521/cissrv_rdo")
import cx_Oracle
# con_CISDB_STDBY = cx_Oracle.connect("DB_USER/DB_PASSWORD@db-host-a.internal.example.com:1521/cis")

CONN_MAX_AGE = 60  # increase the connection timeout to 1 minute

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
        'OPTIONS': {
            'timeout': 60,  # Zvýšte časový limit na 60 sekúnd
            'check_same_thread': False,
        }
    }
}


    #    'cis_db': {
    #     'ENGINE': 'django.db.backends.oracle',
    #     'NAME': 'db-host-a.internal.example.com:1521/cis',
    #     'USER': 'DB_USER',
    #     'PASSWORD': 'DB_PASSWORD',


    # },


DATABASE_ROUTERS = ['project.routers.AppRouter',]
DATABASE_APPS_MAPPING = { '': 'default'}
# DATABASE_APPS_MAPPING = { '': 'default', 'cis_db': 'cis_db'}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'work/static'),

    os.path.join(BASE_DIR, 'eets/static'),
    os.path.join(BASE_DIR, 'edz/static'),

]
STATIC_URL = '/static/'




LOGIN_URL='/signin'
# LOGIN_REDIRECT_URL='/signin'
# import email, smtplib, ssl
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# AUTHENTICATION_BACKENDS = (
#     # Needed to login by username in Django admin, regardless of `allauth`
#     "django.contrib.auth.backends.ModelBackend",

#     # `allauth` specific authentication methods, such as login by e-mail
#     "allauth.account.auth_backends.AuthenticationBackend",
# )
# EMAIL_HOST = 'smtp.internal.example.com'
# EMAIL_HOST_PORT = 25
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'user@example.com'
# EMAIL_HOST_PASSWORD = 'your_gmail_password'

# EMAIL_HOST = 'smtp.internal.example.com'
# EMAIL_HOST_PORT = 25
# EMAIL_USE_TLS = False
# MAIL_USE_SSL = True
# EMAIL_HOST_USER = 'app@example.com'
# EMAIL_HOST_PASSWORD = 'EMAIL_APP_PASSWORD'



# MEDIA_URL = "\\fileserver.internal.example.com/billien/CIS/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

PAYWELL_URL = '/PAYWELL/'
PAYWELL_ROOT = os.path.join(BASE_DIR, 'PAYWELL')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'sk'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_L10N = True

USE_TZ = False

USE_TZ = True

DATE_FORMAT = 'd.m.Y'
# TIME_FORMAT = 'P'
# DATETIME_FORMAT = 'N j, Y, P'
# YEAR_MONTH_FORMAT = 'F Y'
# MONTH_DAY_FORMAT = 'F j'
# SHORT_DATE_FORMAT = 'd.m.Y'
# SHORT_DATETIME_FORMAT = 'd.m.Y P' #'m/d/Y P'
#FIRST_DAY_OF_WEEK = 0 # Monday # je tak uz default

# DATE_INPUT_FORMATS = ('%d.%m.%Y',)
# DATE_FORMAT = 'd.m.Y'
# DATETIME_FORMAT = 'd.m.Y H:i'

DATE_INPUT_FORMATS = [
    '%d.%m-%Y'
    # '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', # '2006-10-25', '10/25/2006', '10/25/06'
    # '%b %d %Y', '%b %d, %Y',            # 'Oct 25 2006', 'Oct 25, 2006'
    # '%d %b %Y', '%d %b, %Y',            # '25 Oct 2006', '25 Oct, 2006'
    # '%B %d %Y', '%B %d, %Y',            # 'October 25 2006', 'October 25, 2006'
    # '%d %B %Y', '%d %B, %Y',            # '25 October 2006', '25 October, 2006'
]
DATETIME_INPUT_FORMATS = [
    '%d.%m.%Y %H:%M:%S',              # '25.10.2006 14:30:59'
    # '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    # '%Y-%m-%d %H:%M:%S.%f',  # '2006-10-25 14:30:59.000200'
    # '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    # '%Y-%m-%d',              # '2006-10-25'
    # '%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
    # '%m/%d/%Y %H:%M:%S.%f',  # '10/25/2006 14:30:59.000200'
    # '%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
    # '%m/%d/%Y',              # '10/25/2006'
    # '%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
    # '%m/%d/%y %H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    # '%m/%d/%y %H:%M',        # '10/25/06 14:30'
    # '%m/%d/%y',              # '10/25/06'
]
# DATETIME_INPUT_FORMATS = ('%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M', '%d/%m/%Y',
#                           '%d/%m/%y %H:%M:%S', '%d/%m/%y %H:%M', '%d/%m/%y',
#                           '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M', '%Y-%m-%d')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


# Konfigurácia APScheduler
SCHEDULER_CONFIG = {
    'apscheduler.jobstores.default': {
        'class': 'django_apscheduler.jobstores:DjangoJobStore',
    },
    'apscheduler.executors.processpool': {
        'class': 'apscheduler.executors.pool:ProcessPoolExecutor',
        'max_workers': 5,  # Upravte podľa potreby
    },
    'apscheduler.executors.default': {
        'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
        'max_workers': 10,  # Upravte podľa potreby
    }
}

SCHEDULER_CONFIG_EDZ = {
    'apscheduler.jobstores.default': {
        'class': 'django_apscheduler.jobstores:DjangoJobStore',
    },
    'apscheduler.executors.processpool': {
        'class': 'apscheduler.executors.pool:ProcessPoolExecutor',
        'max_workers': 5
    },
    'apscheduler.executors.default': {
        'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
        'max_workers': 10
    }
}

SCHEDULER_CONFIG_EETS = {
    'apscheduler.jobstores.default': {
        'class': 'django_apscheduler.jobstores:DjangoJobStore',
    },
    'apscheduler.executors.processpool': {
        'class': 'apscheduler.executors.pool:ProcessPoolExecutor',
        'max_workers': 5
    },
    'apscheduler.executors.default': {
        'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
        'max_workers': 10
    }
}
# SCHEDULER_CONFIG = {
#     'apscheduler.jobstores.default': {
#         'class': 'apscheduler.job:DjangoJobStore',
  
#     },
#     'apscheduler.executors.default': {
#         'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
#         'max_workers': 10
#     },
#     'apscheduler.executors.processpool': {
#         'class': 'apscheduler.executors.pool:ProcessPoolExecutor',
#         'max_workers': 5

#     }

# }
SCHEDULER_AUTOSTART = True

####### LOGGING ##################################
import os
import logging
from logging.handlers import TimedRotatingFileHandler
from datetime import datetime

# Definujte cestu k priečinku 'logs'
LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Vytvorenie priečinka, ak neexistuje
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_info': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'info.log'),  # Používame statický názov, handler sa postará o rotáciu
            'when': 'midnight',
            'interval': 1,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_info'],
            'level': 'ERROR',  # Môžete zmeniť na 'INFO', ak chcete zaznamenávať aj info správy
            'propagate': True,
        },
        'my_app': {  # Pridajte vlastný logger pre vašu aplikáciu
            'handlers': ['file_info', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}






# ####### LOGGING ##################################
# import os
# import logging
# from logging.handlers import TimedRotatingFileHandler
# from datetime import datetime

# # Definujte cestu k priečinku 'logs'
# LOG_DIR = os.path.join(BASE_DIR, 'logs')

# # Vytvorenie priečinka, ak neexistuje
# if not os.path.exists(LOG_DIR):
#     os.makedirs(LOG_DIR)

# # Aktuálny dátum pre názov dnešného súboru
# # current_date = datetime.now().strftime("%d%m%Y")

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple',
#         },
#         'file_info': {
#             'level': 'INFO',
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'filename': os.path.join(LOG_DIR, f'info_{datetime.now().strftime("%d%m%Y")}.log'),
#             'when': 'midnight',
#             'interval': 1,
#             'backupCount': 7,
#             'formatter': 'verbose',
#             'encoding': 'utf-8',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'file_info'],
#             'level': 'ERROR',  # Môžete zmeniť na 'INFO', ak chcete zaznamenávať aj info správy
#             'propagate': True,
#         },
#         'my_app': {  # Pridajte vlastný logger pre vašu aplikáciu
#             'handlers': ['file_info', 'console'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#     },
# }

