# Generated by Django 3.2.23 on 2024-02-22 10:14

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EETSDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('EETS_username', models.CharField(default='Name_Surname', max_length=30)),
                ('EETS_password', encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01')),
                ('EETS_hostname', models.CharField(default='oradb-a01.infra.internal.example.com', max_length=30)),
                ('EETS_port', models.CharField(default='1521', max_length=30)),
                ('EETS_servicename', models.CharField(default='primary_bill.infra.internal.example.com', max_length=30)),
            ],
        ),
    ]
