# Generated by Django 3.2.23 on 2024-02-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eetsdb',
            old_name='EETS_hostname',
            new_name='EETSDB_hostname',
        ),
        migrations.RenameField(
            model_name='eetsdb',
            old_name='EETS_password',
            new_name='EETSDB_password',
        ),
        migrations.RenameField(
            model_name='eetsdb',
            old_name='EETS_port',
            new_name='EETSDB_port',
        ),
        migrations.RenameField(
            model_name='eetsdb',
            old_name='EETS_servicename',
            new_name='EETSDB_servicename',
        ),
        migrations.RenameField(
            model_name='eetsdb',
            old_name='EETS_username',
            new_name='EETSDB_username',
        ),
    ]
