# Generated by Django 3.2.23 on 2024-04-12 13:02

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eets', '0002_auto_20240222_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAIDAMDDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('SAIDAMD_username', models.CharField(default='Name_Surname', max_length=30)),
                ('SAIDAMD_password', encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01')),
                ('SAIDAMD_hostname', models.CharField(default='oradb-a01.infra.internal.example.com', max_length=30)),
                ('SAIDAMD_port', models.CharField(default='1521', max_length=30)),
                ('SAIDAMD_servicename', models.CharField(default='primary_md.infra.internal.example.com', max_length=30)),
            ],
        ),
    ]
