# Generated by Django 3.2.23 on 2024-04-13 21:14

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eets', '0003_saidamddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROXYDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('PROXYDB_username', models.CharField(default='Name_Surname', max_length=30)),
                ('PROXYDB_password', encrypted_model_fields.fields.EncryptedCharField(default='YourPassword#01')),
                ('PROXYDB_hostname', models.CharField(default='oradb-a01.infra.internal.example.com', max_length=30)),
                ('PROXYDB_port', models.CharField(default='1521', max_length=30)),
                ('PROXYDB_servicename', models.CharField(default='primary_proxy.infra.internal.example.com', max_length=30)),
            ],
        ),
    ]
