# Generated by Django 3.2.23 on 2024-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eets', '0004_proxydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxydb',
            name='PROXYDB_servicename',
            field=models.CharField(default='primary_proxy.infra.internal.example.com', max_length=40),
        ),
    ]
